language: ruby

script: ruby test/thinreports-rails_test.rb

sudo: false

rvm:
  - 2.4.1
  - 2.3.1
  - 2.2.4
  - 2.1

gemfile:
  - gemfiles/Gemfile-rails.3.0.x
  - gemfiles/Gemfile-rails.3.1.x
  - gemfiles/Gemfile-rails.3.2.x
  - gemfiles/Gemfile-rails.4.0.x
  - gemfiles/Gemfile-rails.4.1.x
  - gemfiles/Gemfile-rails.4.2.x
  - gemfiles/Gemfile-rails.5.0.x
  - gemfiles/Gemfile-rails.5.1.x
  - gemfiles/Gemfile-rails.5.2.x

matrix:
  include:
    - rvm: 2.5.6
      gemfile: gemfiles/Gemfile-rails.6.0.x
    - rvm: 2.6.4
      gemfile: gemfiles/Gemfile-rails.6.0.x
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/Gemfile-rails.5.0.x
    - rvm: 2.1
      gemfile: gemfiles/Gemfile-rails.5.1.x
    - rvm: 2.1
      gemfile: gemfiles/Gemfile-rails.5.2.x
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile-rails.3.0.x
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile-rails.3.1.x
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile-rails.3.2.x
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile-rails.4.0.x
    - rvm: 2.4.1
      gemfile: gemfiles/Gemfile-rails.4.1.x
